apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "common.fullname" (dict "Chart" .Chart "Values" .Values "Release" .Release "Component" "chat-db") }}
  namespace: {{ include "common.namespace" (dict "Values" .Values "Release" .Release "Component" "chat") }}
  labels:
    {{- include "common.labels" (dict "Chart" .Chart "Release" .Release "Component" "chat-db") | nindent 4 }}
spec:
  serviceName: {{ include "common.fullname" (dict "Chart" .Chart "Values" .Values "Release" .Release "Component" "chat-db") }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "common.selectorLabels" (dict "Release" .Release "Component" "chat-db") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.selectorLabels" (dict "Release" .Release "Component" "chat-db") | nindent 8 }}
    spec:
      serviceAccountName: {{ include "common.serviceAccountName" (dict "Values" .Values "Release" .Release "Component" "chat-db") }}
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: {{ include "common.dbSecretName" (dict "Release" .Release "Component" "chat") }}
              key: chat-db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "common.dbSecretName" (dict "Release" .Release "Component" "chat") }}
              key: chat-db-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "common.dbSecretName" (dict "Release" .Release "Component" "chat") }}
              key: chat-db-password
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.persistence.storageClass | default "standard" }}
      resources:
        requests:
          storage: {{ .Values.persistence.size | default "512Mi" }}