apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-chat-db
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-chat-db
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ .Release.Name }}-chat-db
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-chat-db
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-chat-db
        release: {{ .Release.Name }}
    spec:
        serviceAccountName: {{ .Values.serviceAccount.dbName | default "default" }}
        containers:
          - name: postgres
            image: postgres:13
            imagePullPolicy: IfNotPresent
            ports:
            - containerPort: 5432
              name: db
            env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.database.name }}
                  key: chat-db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.database.user }}
                  key: chat-db-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.database.password }}
                  key: chat-db-password
            volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.persistence.storageClass | default "standard" }}
      resources:
        requests:
          storage: {{ .Values.persistence.size | default "512Mi" }}