apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-chat
  namespace: {{ .Values.namespace }}
  labels:
    app: chat
    {{- include "chat-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: chat
      {{- include "chat-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: chat
        {{- include "chat-service.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Release.Name }}-chat-server
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-chat-configmap
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}