apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" (dict "Chart" .Chart "Values" .Values "Release" .Release "Component" "chat") }}
  namespace: {{ include "common.namespace" (dict "Values" .Values "Release" .Release "Component" "chat") }}
  labels:
    {{- include "common.labels" (dict "Chart" .Chart "Release" .Release "Component" "chat") | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" (dict "Release" .Release "Component" "chat") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.selectorLabels" (dict "Release" .Release "Component" "chat") | nindent 8 }}
    spec:
      serviceAccountName: {{ include "common.serviceAccountName" (dict "Values" .Values "Release" .Release "Component" "chat") }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - configMapRef:
                name: {{ include "common.fullname" (dict "Chart" .Chart "Values" .Values "Release" .Release "Component" "chat-configmap") }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}