apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chat-service.fullname" . }}-configmap
  namespace: {{ include "chat-service-chart.namespace" . }}
  labels:
    {{- include "chat-service.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.configMap.data }}
  {{ $key }}: {{ tpl $val $ | quote }}
  {{- end }}