apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chat-service.fullname" . }}-configmap
  namespace: {{ .Values.namespace }} # Changed from .Values.namespace
  labels:
    {{- include "chat-service.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.configMap.data }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}