{{- if .Values.ingress.enabled }}
# HTTPS IngressRoute
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-chat-ingressroute
  namespace: {{ include "chat-service-chart.namespace" . }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certManager.clusterIssuer }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: PathPrefix(`/api/chat`)
      kind: Rule
      priority: 1000
      services:
        - name: {{ .Release.Name }}-chat-service
          port: {{ .Values.service.port }}
          sticky:
            cookie:
              name: chat_sticky
      middlewares:
        - name: {{ .Release.Name }}-strip-prefix
          namespace: {{ include "chat-service-chart.namespace" . }}
  tls:
    {{- if .Values.ingress.tls.enabled }}
    secretName: {{ .Values.ingress.tls.secretName }}
    {{- end }}
---
# HTTP to HTTPS redirect IngressRoute
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-chat-ingressroute-http
  namespace: {{ include "chat-service-chart.namespace" . }}
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/api/chat`)
      kind: Rule
      middlewares:
        - name: {{ .Release.Name }}-strip-prefix
          namespace: {{ include "chat-service-chart.namespace" . }}
        - name: {{ .Release.Name }}-redirect-https
          namespace: {{ include "chat-service-chart.namespace" . }}
      services:
        - name: {{ .Release.Name }}-chat-service
          port: {{ .Values.service.port }}
{{- end }}
