apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chat-service.fullname" . }}-secrets # Use fullname helper
  namespace: {{ .Values.namespace }} # Changed from .Values.namespace
  labels:
    {{- include "chat-service.labels" . | nindent 4 }}
type: Opaque
data:
  DB_NAME: {{ .Values.secrets.database.name | b64enc | quote }}
  DB_USER: {{ .Values.secrets.database.user | b64enc | quote }}
  DB_PASSWORD: {{ .Values.secrets.database.password | b64enc | quote }}
  ADMIN_USERNAME: {{ .Values.secrets.admin.username | b64enc | quote }}
  ADMIN_PASSWORD: {{ .Values.secrets.admin.password | b64enc | quote }}
  ADMIN_EMAIL: {{ .Values.secrets.admin.email | b64enc | quote }}
  SECRET_KEY: {{ .Values.secrets.admin.secretKey | b64enc | quote }}
  SERVICE_PASSWORD: {{ .Values.secrets.servicePassword | b64enc | quote }}
