{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-chat-server
  namespace: {{ .Values.namespace }}
  labels:
    app: chat-server
    {{- include "chat-service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-chat-db
  namespace: {{ .Values.namespace }}
  labels:
    app: chat-db
    {{- include "chat-service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.dbAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.dbAutomount }}
{{- end }}