apiVersion: v1
kind: Secret
metadata:
  name: login-db-secret
  namespace: login-namespace
type: Opaque
data:
  login-db: bG9naW5fZGI= # base64 encoded string
  login-db-user: cGFzcXVhbGU=
  login-db-password: MTIzNDU2
---
apiVersion: v1
kind: Secret
metadata:
  name: login-secret
  namespace: login-namespace
type: Opaque
data:
  client_id: ZklkeVpJUk5sLVpkQ1Z4d1RzN1V0Y1RmQ3lfZ1dWUXBSX0pNbHI5YWhvOA==
  client_secret: T0VUMERyd2Q5dnRDaEJqdW5MdnJWZkdzZjNuQ3RTT0JBbVZhdVBPZk1xVWtjT2JrQzlfMlZGdnNmYnUtMHJEYm56OWxENXRwRXZHSnc1blNjc0dqR3c=
---
apiVersion: v1
kind: Secret
metadata:
  name: elastic-credentials
  namespace: elk
type: Opaque
data:
  username: cGFzcXVhbGUK
  password: QrYz0aoF398SWi4E6fK9W810
---
apiVersion: v1
kind: Secret
metadata:
  name: kibana-credentials
  namespace: elk
type: Opaque
data:
  elasticsearch.password: QrYz0aoF398SWi4E6fK9W810  # base64
---
apiVersion: v1
kind: Secret
metadata:
  name: logstash-secret
  namespace: elk
type: Opaque
data:
  ES_USER: cGFzcXVhbGUK
  ES_PASSWORD: QrYz0aoF398SWi4E6fK9W810
  elastic: QrYz0aoF398SWi4E6fK9W810