apiVersion: skaffold/v4beta12
kind: Config
metadata:
    name: trascendence-frontend
build:
    artifacts:
        - image: marcor42/frontend
          context: Front-End
          docker:
              dockerfile: Dockerfile
    local:
        push: false
        useDockerCLI: true
manifests:
    rawYaml:
        - Manifests/front-end-deployment.yaml
