apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frontend-configmap
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $val := .Values.configMap.data }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}