apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-chat
  namespace: {{ .Values.namespace }}
  labels:
    app: chat
    {{- include "chat-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: chat
      {{- include "chat-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: chat
        {{- include "chat-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-chat-db-secret
                  key: chat-db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-chat-db-secret
                  key: chat-db-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-chat-db-secret
                  key: chat-db-password
            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-chat-admin
                  key: admin_username
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-chat-admin
                  key: admin_password
            - name: ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-chat-admin
                  key: admin_email
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-chat-admin
                  key: secret-key
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-chat-configmap
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}