{{- if .Values.ingress.enabled }}
# HTTPS IngressRoute for Frontend
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-frontend-ingressroute
  namespace: {{ include "front-end-chart.namespace" . }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certManager.clusterIssuer }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
    # WebSocket route for Vite HMR (higher priority)
    - match: Host(`{{ .Values.ingress.host }}`) && (PathPrefix(`/@vite/client`) || PathPrefix(`/ws`) || Headers(`Connection`, `Upgrade`))
      kind: Rule
      priority: 600  # Higher priority for WebSocket routes
      services:
        - name: {{ .Release.Name }}-frontend-service
          port: {{ .Values.service.port }}
      middlewares:
        - name: {{ .Release.Name }}-vite-hmr
          namespace: {{ include "front-end-chart.namespace" . }}
        - name: {{ .Release.Name }}-websocket-headers
          namespace: {{ include "front-end-chart.namespace" . }}
    # Regular HTTP route (lower priority)
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      priority: 500  # Lower priority than WebSocket routes
      services:
        - name: {{ .Release.Name }}-frontend-service
          port: {{ .Values.service.port }}
          sticky:
            cookie:
              name: frontend_sticky
  tls:
    {{- if .Values.ingress.tls.enabled }}
    secretName: {{ .Values.ingress.tls.secretName }}
    {{- end }}
---
# HTTP to HTTPS redirect IngressRoute for Frontend
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-frontend-ingressroute-http
  namespace: {{ include "front-end-chart.namespace" . }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      middlewares:
        - name: {{ .Release.Name }}-redirect-https
          namespace: {{ include "front-end-chart.namespace" . }}
      services:
        - name: {{ .Release.Name }}-frontend-service
          port: {{ .Values.service.port }}
{{- end }}
