{{- if .Values.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "front-end-chart.namespace" . }}-{{ .Release.Name }}-websocket-headers
  namespace: {{ include "front-end-chart.namespace" . }}
  labels:
    {{- include "front-end-chart.labels" . | nindent 4 }}
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      X-Forwarded-Port: "443"
      Connection: "Upgrade"
      Upgrade: "websocket"
    customResponseHeaders:
      X-Frame-Options: "SAMEORIGIN"
      X-Content-Type-Options: "nosniff"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "front-end-chart.namespace" . }}-{{ .Release.Name }}-redirect-https
  namespace: {{ include "front-end-chart.namespace" . }}
  labels:
    {{- include "front-end-chart.labels" . | nindent 4 }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "front-end-chart.namespace" . }}-{{ .Release.Name }}-vite-hmr
  namespace: {{ include "front-end-chart.namespace" . }}
  labels:
    {{- include "front-end-chart.labels" . | nindent 4 }}
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      X-Forwarded-Host: "trascendence.42firenze.it"
      Connection: "Upgrade"
      Upgrade: "websocket"
      Sec-WebSocket-Extensions: ""
      Sec-WebSocket-Key: ""
      Sec-WebSocket-Version: ""
{{- end }}