{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common.serviceAccountName" (dict "Chart" .Chart "Values" .Values "Release" .Release "Component" "frontend") }}
  namespace: {{ include "common.namespace" (dict "Values" .Values "Release" .Release "Component" "frontend") }}
  labels:
    {{- include "common.labels" (dict "Chart" .Chart "Values" .Values "Release" .Release "Component" "frontend") | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}