apiVersion: v1
kind: ConfigMap
metadata:
  name: login-configmap
  namespace: login-namespace
data:
  login_url: login-service
  chat_url: chat-service
  users_url: users-service
  notifications_url: notifications-service
  login_db: login-db-service
  redis: redis-service
  redis_port: "6379"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: front-end-configmap
  namespace: front-end-namespace
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-configmap
  namespace: chat
data:
  login_url: login-service
  chat_url: chat-service
  users_url: users-service
  notifications_url: notifications-service
  chat_db: chat-db-service
  redis: redis-service
  redis_port: "6379"
