apiVersion: v1
kind: Namespace
metadata:
  name: login
---
apiVersion: v1
kind: Namespace
metadata:
  name: front-end-namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: elk
---
apiVersion: v1
kind: Namespace
metadata:
  name: chat
---
apiVersion: v1
kind: Namespace
metadata:
  name: redis-namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: minio