apiVersion: v1
kind: Namespace
metadata:
  name: front-end
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: front-end
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      hostAliases:
      - hostnames:
        - trascendence.me
        ip: 192.168.49.2
      containers:
      - name: frontend
        image: marcor42/frontend
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: front-end
spec:
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: vite-hmr
  namespace: front-end
spec:
  headers:
    customRequestHeaders:
      Connection: "Upgrade"
      Upgrade: "websocket"
      X-Forwarded-Proto: "https"
      X-Forwarded-Port: "443"
    customResponseHeaders:
      X-Frame-Options: "SAMEORIGIN"
      X-Content-Type-Options: "nosniff"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: websocket-headers
  namespace: front-end
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      X-Forwarded-Port: "443"
      Connection: "Upgrade"
      Upgrade: "websocket"
    customResponseHeaders:
      X-Frame-Options: "SAMEORIGIN"
      X-Content-Type-Options: "nosniff"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: frontend-ingressroute
  namespace: front-end
spec:
  entryPoints:
    - web
    - websecure
  routes:
     # Route per WebSocket e HMR - priorità alta
    - match: PathPrefix(`/`) && (PathPrefix(`/@vite/client`) || PathPrefix(`/ws`) || Headers(`Connection`, `Upgrade`))
      kind: Rule
      priority: 101
      services:
        - name: frontend-service
          port: 3000
      middlewares:
        - name: vite-hmr
          namespace: front-end
        - name: websocket-headers
          namespace: front-end
    # Route principale - priorità normale
    - match: PathPrefix(`/`)
      kind: Rule
      priority: 100
      services:
        - name: frontend-service
          port: 3000
  tls: {}