apiVersion: v2
name: cert-manager-chart
description: Certificate management for Trascendence
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: cert-manager
    version: "v1.13.3"
    repository: "https://charts.jetstack.io"
    condition: cert-manager.enabled