apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-user-service"
  namespace: {{ include "user-service-chart.namespace" . }}
  labels:
    app: {{ .Release.Name }}-user
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "user-service-chart.selectorLabels" . | nindent 4 }}
    app: {{ include "user-service-chart.name" . }}