apiVersion: v2
name: crds-chart
description: Custom Resource Definitions for Trascendence infrastructure
type: application
version: 0.1.0
appVersion: "1.0"

# This chart installs all necessary CRDs for the Trascendence project
# CRDs should be installed before other charts that depend on them
annotations:
  "helm.sh/hook": pre-install,pre-upgrade
  "helm.sh/hook-weight": "-10"
  "helm.sh/hook-delete-policy": before-hook-creation
