apiVersion: v2
name: observability-chart
description: A Helm chart for observability Stack, Prometheus, and Grafana observability stack
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: eck-elasticsearch
    version: 0.13.0
    repository: https://helm.elastic.co
    condition: eck-elasticsearch.enabled
  - name: eck-kibana
    version: 0.13.0
    repository: https://helm.elastic.co
    condition: eck-kibana.enabled
  - name: eck-logstash
    version: 0.13.0
    repository: https://helm.elastic.co
    condition: eck-logstash.enabled
  - name: filebeat
    version: 8.13.0
    repository: https://helm.elastic.co
    condition: filebeat.enabled
  - name: kube-prometheus-stack
    version: 45.7.1
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
    alias: prometheus
  - name: grafana
    version: 6.50.7
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
