apiVersion: v2
name: observability-chart
description: A Helm chart for observability Stack, Prometheus, and Grafana observability stack
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: kube-prometheus-stack
    version: 75.14.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
    alias: prometheus
