apiVersion: apps/v1
kind: Deployment
metadata:
    name: front-end-deployment
    namespace: front-end-namespace
    labels:
        app: front-end
spec:
    replicas: 1
    selector:
        matchLabels:
            app: front-end
    template:
        metadata:
            labels:
                app: front-end
        spec:
            hostAliases:
                - ip: "192.168.49.2"
                  hostnames:
                      - "trascendence.42firenze.it"
            containers:
                - name: front-end
                  image: marcor42/frontend
                  imagePullPolicy: Always
                  resources:
                      limits:
                          memory: "512Mi"
                          cpu: "500m"
                      requests:
                          memory: "256Mi"
                          cpu: "250m"
                  ports:
                      - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
    name: front-end-service
    namespace: front-end-namespace
spec:
    selector:
        app: front-end
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
