apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: user
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      initContainers:
        - name: init-user-db
          image: busybox
          command: ['sh', '-c', 'until pg_isready -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER -d $POSTGRES_DB; do echo waiting for postgres; sleep 2; done;']
          env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: user-db-secret
                key: user-db
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: user-db-secret
                key: user-db-user
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: user-configmap
                key: user_db
          - name: POSTGRES_PORT
            value: "5432"
      containers:
      - name: user-deployment
        image: bombatomica/user
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: user-db-secret
              key: user-db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: user-db-secret
              key: user-db-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: user-db-secret
              key: user-db-password
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: user-configmap
              key: user_db
        - name: POSTGRES_PORT
          value: "5432"
        - name: LOGIN_SERVICE
          valueFrom:
            configMapKeyRef:
              name: user-configmap
              key: login_url
        - name: USERS_SERVICE
          valueFrom:
            configMapKeyRef:
              name: user-configmap
              key: user_url
        - name: NOTIFICATIONS_SERVICE
          valueFrom:
            configMapKeyRef:
              name: user-configmap
              key: notifications_url
        - name: CHAT_SERVICE
          valueFrom:
            configMapKeyRef:
              name: user-configmap
              key: chat_url
        - name: PONG_SERVICE
          valueFrom:
            configMapKeyRef:
              name: user-configmap
              key: pong_url
        - name: ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: user-admin
              key: admin_username
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: user-admin
              key: admin_password
        - name: ADMIN_EMAIL
          valueFrom:
            secretKeyRef:
              name: user-admin
              key: admin_email
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: user-admin
              key: secret-key
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: user
  labels:
    app: user
spec:
  selector:
    app: user
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000