apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-docs-service.fullname" . }}-configmap
  namespace: {{ include "api-docs-service-chart.namespace" . }}
  labels:
    {{- include "api-docs-service.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}
