{{- if .Values.ingress.enabled -}}
# Strip prefix middleware to remove /api/docs from the path
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-api-docs-strip-prefix
  namespace: {{ include "api-docs-service-chart.namespace" . }}
  labels:
    {{- include "api-docs-service.labels" . | nindent 4 }}
spec:
  stripPrefix:
    prefixes:
      - /api/docs
---
# HTTPS redirect middleware
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-api-docs-redirect-https
  namespace: {{ include "api-docs-service-chart.namespace" . }}
  labels:
    {{- include "api-docs-service.labels" . | nindent 4 }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
# Headers middleware for security
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-api-docs-headers
  namespace: {{ include "api-docs-service-chart.namespace" . }}
  labels:
    {{- include "api-docs-service.labels" . | nindent 4 }}
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      X-Forwarded-Port: "443"
    customResponseHeaders:
      X-Frame-Options: "SAMEORIGIN"
      X-Content-Type-Options: "nosniff"
      X-XSS-Protection: "1; mode=block"
{{- end }}
