{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "api-docs-service.fullname" . }}
  namespace: {{ .Values.serviceMonitor.namespace | default (include "api-docs-service-chart.namespace" .) }}
  labels:
    {{- include "api-docs-service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "api-docs-service.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    path: {{ .Values.serviceMonitor.path }}
  namespaceSelector:
    matchNames:
    - {{ include "api-docs-service-chart.namespace" . }}
{{- end }}
