apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-docs-service.fullname" . }}
  namespace: {{ include "api-docs-service-chart.namespace" . }}
  labels:
    {{- include "api-docs-service.labels" . | nindent 4 }}
    app: {{ include "api-docs-service.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "api-docs-service.selectorLabels" . | nindent 4 }}
    app: {{ include "api-docs-service.name" . }}
