apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-deployment
  namespace: notifications
  labels:
    app: notifications-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-server
  template:
    metadata:
      labels:
        app: notifications-server
    spec:
      initContainers:
      - name: init-notifications-server
        image: busybox
        command: ['sh', '-c', 'echo "Waiting for the database service"; while ! nc -z notifications-db-service 5432; do sleep 1; done; echo "Database service is up and running"']
      containers:
      - name: notifications-server
        image: bombatomica/notifications
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        # readinessProbe:
        #   httpGet:
        #     path: /notifications/health
        #     port: 8000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: notifications-db-secret
              key: notifications-db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: notifications-db-secret
              key: notifications-db-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: notifications-db-secret
              key: notifications-db-password
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: notifications-configmap
              key: notifications_db
        - name: POSTGRES_PORT
          value: "5432"
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: notifications-configmap
              key: redis
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: notifications-configmap
              key: redis_port
        - name: REDIS_DB
          valueFrom:
            configMapKeyRef:
              name: notifications-configmap
              key: redis_db
        - name: LOGIN_URL
          valueFrom:
            configMapKeyRef:
              name: notifications-configmap
              key: login_url
        - name: CHAT_URL
          valueFrom:
            configMapKeyRef:
              name: notifications-configmap
              key: chat_url
        - name: USER_URL
          valueFrom:
            configMapKeyRef:
              name: notifications-configmap
              key: users_url
        - name: NOTIFICATIONS_URL
          valueFrom:
            configMapKeyRef:
              name: notifications-configmap
              key: notifications_url
        - name: PONG_URL
          valueFrom:
            configMapKeyRef:
              name: notifications-configmap
              key: pong_url
        - name: ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: notifications-admin
              key: admin_username
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: notifications-admin
              key: admin_password
        - name: ADMIN_EMAIL
          valueFrom:
            secretKeyRef:
              name: notifications-admin
              key: admin_email
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: notifications-api
              key: secret-key
        - name: DEBUG
          value: "False"
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-service
  namespace: notifications
spec:
  selector:
    app: notifications-server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000