apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-server-deployment
  namespace: login
  labels:
    app: login-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-server
  template:
    metadata:
      labels:
        app: login-server
    spec:
      initContainers:
      - name: init-login-server
        image: busybox
        command: ['sh', '-c', 'echo "Waiting for the database service"; while ! nc -z login-db-service 5432; do sleep 1; done; echo "Database service is up and running"']
      containers:
      - name: login-server
        image: bombatomica/login
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        # readinessProbe:
        #   httpGet:
        #     path: /login/health
        #     port: 8000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: POSTGRES_DB
          valueFrom:
           secretKeyRef:
            name: login-db-secret
            key: login-db
        - name: POSTGRES_USER
          valueFrom:
           secretKeyRef:
            name: login-db-secret
            key: login-db-user
        - name: POSTGRES_PASSWORD
          valueFrom:
           secretKeyRef:
            name: login-db-secret
            key: login-db-password
        - name: LOGIN_URL
          valueFrom:
           configMapKeyRef:
            name: login-configmap
            key: login_url
        - name: CHAT_URL
          valueFrom:
           configMapKeyRef:
            name: login-configmap
            key: chat_url
        - name: USER_URL
          valueFrom:
           configMapKeyRef:
            name: login-configmap
            key: users_url
        - name: NOTIFICATIONS_URL
          valueFrom:
           configMapKeyRef:
            name: login-configmap
            key: notifications_url
        - name: PONG_URL
          valueFrom:
           configMapKeyRef:
            name: login-configmap
            key: pong_url
        - name: POSTGRES_HOST
          valueFrom:
           configMapKeyRef:
            name: login-configmap
            key: login_db
        - name: POSTGRES_PORT
          value: "5432" 
        - name: ADMIN_EMAIL
          valueFrom:
           secretKeyRef:
            name: login-secret
            key: admin_email
        - name: ADMIN_PASSWORD
          valueFrom:
           secretKeyRef:
            name: login-secret
            key: admin_password
        - name: ADMIN_USERNAME
          valueFrom:
           secretKeyRef:
            name: login-secret
            key: admin_username
        - name: SECRET_KEY
          valueFrom:
           secretKeyRef:
            name: login-api
            key: secret-key
        - name: DEBUG
          value: "False"
---
apiVersion: v1
kind: Service
metadata:
  name: login-service
  namespace: login
spec:
  selector:
    app: login-server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000