apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-db-deployment
  namespace: chat
  labels:
    app: chat-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-db
  template:
    metadata:
      labels:
        app: chat-db
    spec:
      containers:
      - name: chat-db
        image: postgres
        ports:
        - containerPort: 5432
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: POSTGRES_DB
          valueFrom:
           secretKeyRef:
            name: chat-db-secret
            key: chat-db
        - name: POSTGRES_USER
          valueFrom:
           secretKeyRef:
            name: chat-db-secret
            key: chat-db-user
        - name: POSTGRES_PASSWORD
          valueFrom:
           secretKeyRef:
            name: chat-db-secret
            key: chat-db-password
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: chat-db-service
  namespace: chat
spec:
  selector:
    app: chat-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: chat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  volumeName: postgres-pv

