apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-deployment
  namespace: chat
  labels:
    app: chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
      - name: chat-deployment
        image: samybravy/chat
        ports:
        - containerPort: 8000
    env:
    - name: POSTGRES_DB
      valueFrom:
        secretKeyRef:
          name: chat-secret
          key: POSTGRES_DB
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: chat-secret
          key: POSTGRES_USER
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: chat-secret
          key: POSTGRES_PASSWORD
    - name: POSTGRES_HOST
      valueFrom:
        configMapKeyRef:
            name: chat-configmap
            key: chat_db
    - name: POSTGRES_PORT
      value: "5432"
    - name: REDIS_HOST
      valueFrom:
        configMapKeyRef:
            name: chat-configmap
            key: redis
    - name: REDIS_PORT
      valueFrom:
        configMapKeyRef:
                name: chat-configmap
                key: redis_port