apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notifications-service-chart.fullname" . }}-config
  namespace: {{ include "notifications-service-chart.namespace" . }}
  labels:
    {{- include "notifications-service-chart.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: {{ tpl $value $ | quote }}
  {{- end }}
