{{- if .Values.db.exporter.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "notifications-service-chart.fullname" . }}-db-metrics
  namespace: {{ include "notifications-service-chart.namespace" . }}
  labels:
    app: {{ .Release.Name }}-notifications-db
    {{- include "notifications-service-chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-notifications-db
      {{- include "notifications-service-chart.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
{{- end }}
