apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-notifications-db-service
  namespace: {{ include "notifications-service-chart.namespace" . }}
  labels:
    app: {{ .Release.Name }}-notifications-db
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.db.service.port }}
    targetPort: {{ .Values.db.service.port }}
    protocol: TCP
    name: postgres
  {{- if .Values.db.exporter.enabled }}
  - port: 9187
    targetPort: 9187
    protocol: TCP
    name: postgres-exporter
  {{- end }}
  selector:
    app: {{ .Release.Name }}-notifications-db
    release: {{ .Release.Name }}