apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notifications-service-chart.fullname" . }}-secrets
  namespace: {{ include "notifications-service-chart.namespace" . }}
  labels:
    {{- include "notifications-service-chart.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_DB: {{ .Values.secrets.databases.notifications.name | b64enc | quote }}
  POSTGRES_USER: {{ .Values.secrets.databases.notifications.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.databases.notifications.password | b64enc | quote }}
  ADMIN_USERNAME: {{ .Values.secrets.admin.username | b64enc | quote }}
  ADMIN_PASSWORD: {{ .Values.secrets.admin.password | b64enc | quote }}
  ADMIN_EMAIL: {{ .Values.secrets.admin.email | b64enc | quote }}
  SECRET_KEY: {{ .Values.secrets.serviceAuth.secretKey | b64enc | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.secrets.oauth.google.clientId | b64enc | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.oauth.google.clientSecret | b64enc | quote }}
  42_CLIENT_ID: {{ .Values.secrets.oauth.fortytwo.clientId | b64enc | quote }}
  42_CLIENT_SECRET: {{ .Values.secrets.oauth.fortytwo.clientSecret | b64enc | quote }}
  SERVICE_PASSWORD: {{ .Values.secrets.serviceAuth.password | b64enc | quote }}