{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.dbName | default "notifications-db-service-account" }}
  namespace: {{ include "notifications-service-chart.namespace" . }}
  labels:
    app: {{ .Release.Name }}-notifications-db-db
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- with .Values.serviceAccount.dbAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.dbAutomount }}
{{- end }}