{{- if index .Values "eck-elasticsearch" "enabled" }}
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ index .Values "eck-elasticsearch" "fullnameOverride" }}
  namespace: {{ .Values.global.namespace.name }}
  labels:
    {{- include "observability-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: elasticsearch
spec:
  version: {{ index .Values "eck-elasticsearch" "version" }}
  nodeSets:
  {{- range (index .Values "eck-elasticsearch" "nodeSets") }}
  - name: {{ .name }}
    count: {{ .count }}
    {{- if .config }}
    config:
      {{- toYaml .config | nindent 6 }}
    {{- end }}
    {{- if .podTemplate }}
    podTemplate:
      {{- toYaml .podTemplate | nindent 6 }}
    {{- end }}
    {{- if .volumeClaimTemplates }}
    volumeClaimTemplates:
    {{- range .volumeClaimTemplates }}
    - metadata:
        name: {{ .metadata.name }}
      spec:
        accessModes:
        {{- range .spec.accessModes }}
        - {{ . }}
        {{- end }}
        resources:
          requests:
            storage: {{ .spec.resources.requests.storage }}
        {{- if .spec.storageClassName }}
        storageClassName: {{ .spec.storageClassName }}
        {{- end }}
    {{- end }}
    {{- end }}
  {{- end }}
  {{- if .Values.global.tls.enabled }}
  http:
    tls:
      selfSignedCertificate:
        disabled: false
  {{- end }}
{{- end }}
