{{- if .Values.filebeat.customEnabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: {{ .Values.global.namespace.name }}
  labels:
    {{- include "observability-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: filebeat
data:
  filebeat.yml: |
{{ index .Values.filebeat.filebeatConfig "filebeat.yml" | indent 4 }}

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: {{ .Values.global.namespace.name }}
  labels:
    {{- include "observability-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: filebeat
spec:
  selector:
    matchLabels:
      {{- include "observability-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: filebeat
  template:
    metadata:
      labels:
        {{- include "observability-chart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: filebeat
    spec:
      serviceAccountName: filebeat
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:{{ index .Values "eck-elasticsearch" "version" }}
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        env:
        {{- range .Values.filebeat.extraEnvs }}
        - name: {{ .name }}
          {{- if .value }}
          value: {{ .value | quote }}
          {{- else if .valueFrom }}
          valueFrom:
            {{- toYaml .valueFrom | nindent 12 }}
          {{- end }}
        {{- end }}
        securityContext:
          runAsUser: 0
          privileged: true
        resources:
          {{- toYaml .Values.filebeat.resources | nindent 10 }}
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: dockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        {{- if .Values.filebeat.livenessProbe }}
        livenessProbe:
          {{- toYaml .Values.filebeat.livenessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.filebeat.readinessProbe }}
        readinessProbe:
          {{- toYaml .Values.filebeat.readinessProbe | nindent 10 }}
        {{- end }}
      volumes:
      - name: config
        configMap:
          defaultMode: 0640
          name: filebeat-config
      - name: data
        hostPath:
          path: /var/lib/filebeat-data
          type: DirectoryOrCreate
      - name: varlog
        hostPath:
          path: /var/log
          type: Directory
      - name: dockercontainers
        hostPath:
          path: /var/lib/docker/containers
          type: Directory

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: {{ .Values.global.namespace.name }}
  labels:
    {{- include "observability-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: filebeat

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat
  labels:
    {{- include "observability-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: filebeat
rules:
{{- range .Values.filebeat.clusterRoleRules }}
- apiGroups:
  {{- range .apiGroups }}
  - {{ . | quote }}
  {{- end }}
  resources:
  {{- range .resources }}
  - {{ . | quote }}
  {{- end }}
  verbs:
  {{- range .verbs }}
  - {{ . | quote }}
  {{- end }}
{{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat
  labels:
    {{- include "observability-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: filebeat
subjects:
- kind: ServiceAccount
  name: filebeat
  namespace: {{ .Values.global.namespace.name }}
roleRef:
  kind: ClusterRole
  name: filebeat
  apiGroup: rbac.authorization.k8s.io
{{- end }}
