{{- if .Values.grafana.enabled }}
---
# Grafana Datasource Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-grafana-datasources
  namespace: {{ .Release.Namespace }}
  labels:
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://{{ .Release.Name }}-prometheus-prometheus:9090
        isDefault: true
        editable: true
        jsonData:
          httpMethod: POST
          manageAlerts: true
          prometheusType: Prometheus
          prometheusVersion: 2.42.0
                    cacheLevel: 'High'
          disableRecordingRules: false
          incrementalQueryOverlapWindow: 10m
      
      {{- if index .Values "elasticsearch" "enabled" }}
      - name: Elasticsearch
        type: elasticsearch
        access: proxy
        url: http://{{ .Release.Name }}-elasticsearch:9200
        database: "[logstash-]YYYY.MM.DD"
        basicAuth: false
        jsonData:
          esVersion: "8.5.1"
          timeField: "@timestamp"
          logMessageField: message
          logLevelField: level
      {{- end }}
{{- end }}
