{{- if .Values.ingressroutes.enabled }}
# Middleware for HTTPS redirect
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "observability-chart.fullname" . }}-redirect-https
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability-chart.labels" . | nindent 4 }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
# Middleware for Grafana StripPrefix
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "observability-chart.fullname" . }}-grafana-strip-prefix
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability-chart.labels" . | nindent 4 }}
spec:
  stripPrefix:
    prefixes:
      - /grafana
---
# Grafana HTTPS IngressRoute
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "observability-chart.fullname" . }}-grafana-https
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  entryPoints:
    - websecure
  routes:
    - match: PathPrefix(`/grafana`)
      kind: Rule
      priority: 1000
      services:
        - name: {{ .Release.Name }}-prometheus-grafana
          port: 80
      middlewares:
        - name: {{ include "observability-chart.fullname" . }}-grafana-strip-prefix
          namespace: {{ .Release.Namespace }}
  tls:
    secretName: grafana-tls
---
# Grafana HTTP to HTTPS redirect
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "observability-chart.fullname" . }}-grafana-http
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/grafana`)
      kind: Rule
      priority: 1000
      middlewares:
        - name: {{ include "observability-chart.fullname" . }}-redirect-https
          namespace: {{ .Release.Namespace }}
      services:
        - name: {{ .Release.Name }}-prometheus-grafana
          port: 80
{{- end }}