{{- if .Values.ingress.enabled }}
# Grafana IngressRoute
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "observability-chart.fullname" . }}-grafana
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`grafana.trascendence.local`)
      kind: Rule
      services:
        - name: {{ include "observability-chart.fullname" . }}-grafana
          port: 80
  tls:
    secretName: grafana-tls
---
# Grafana HTTP to HTTPS redirect
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "observability-chart.fullname" . }}-grafana-http
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`grafana.trascendence.local`)
      kind: Rule
      middlewares:
        - name: {{ include "observability-chart.fullname" . }}-redirect-https
          namespace: {{ .Release.Namespace }}
      services:
        - name: {{ include "observability-chart.fullname" . }}-grafana
          port: 80
---
# Kibana IngressRoute
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "observability-chart.fullname" . }}-kibana
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: kibana
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`kibana.trascendence.local`)
      kind: Rule
      services:
        - name: eck-kibana-kb-http
          port: 5601
          serversTransport: kibana-tls-transport
      middlewares:
        - name: {{ include "observability-chart.fullname" . }}-kibana-headers
          namespace: {{ .Release.Namespace }}
  tls:
    secretName: kibana-tls
---
# Kibana HTTP to HTTPS redirect
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "observability-chart.fullname" . }}-kibana-http
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: kibana
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`kibana.trascendence.local`)
      kind: Rule
      middlewares:
        - name: {{ include "observability-chart.fullname" . }}-redirect-https
          namespace: {{ .Release.Namespace }}
      services:
        - name: eck-kibana-kb-http
          port: 5601
---
# Middleware for HTTPS redirect
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "observability-chart.fullname" . }}-redirect-https
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability-chart.labels" . | nindent 4 }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
# Middleware for Kibana headers
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "observability-chart.fullname" . }}-kibana-headers
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability-chart.labels" . | nindent 4 }}
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      X-Forwarded-Port: "443"
    customResponseHeaders:
      X-Frame-Options: "SAMEORIGIN"
      X-Content-Type-Options: "nosniff"
---
# ServersTransport for Kibana HTTPS backend
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: kibana-tls-transport
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability-chart.labels" . | nindent 4 }}
spec:
  serverName: "eck-kibana-kb-http"
  insecureSkipVerify: true
{{- end }}
