{{- if .Values.ingressroutes.enabled }}
# Middleware for HTTPS redirect
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "observability-chart.fullname" . }}-redirect-https
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability-chart.labels" . | nindent 4 }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
# Middleware for Grafana StripPrefix
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "observability-chart.fullname" . }}-grafana-strip-prefix
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability-chart.labels" . | nindent 4 }}
spec:
  stripPrefix:
    prefixes:
      - /grafana
---
# # Middleware for Kibana StripPrefix
# apiVersion: traefik.io/v1alpha1
# kind: Middleware
# metadata:
#   name: {{ include "observability-chart.fullname" . }}-kibana-strip-prefix
#   namespace: {{ .Release.Namespace }}
#   labels:
#     {{- include "observability-chart.labels" . | nindent 4 }}
# spec:
#   stripPrefix:
#     prefixes:
#       - /kibana
# ---
# Middleware for Kibana headers
# apiVersion: traefik.io/v1alpha1
# kind: Middleware
# metadata:
#   name: {{ include "observability-chart.fullname" . }}-kibana-headers
#   namespace: {{ .Release.Namespace }}
#   labels:
#     {{- include "observability-chart.labels" . | nindent 4 }}
# spec:
#   headers:
#     customRequestHeaders:
#       X-Forwarded-Proto: "https"
#       X-Forwarded-Port: "443"
#     customResponseHeaders:
#       X-Frame-Options: "SAMEORIGIN"
#       X-Content-Type-Options: "nosniff"
# ---
# Grafana IngressRoute
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "observability-chart.fullname" . }}-grafana
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: PathPrefix(`/grafana`)
      kind: Rule
      priority: 1000
      services:
        - name: {{ .Release.Name }}-grafana
          port: 80
      middlewares:
        - name: {{ include "observability-chart.fullname" . }}-grafana-strip-prefix
          namespace: {{ .Release.Namespace }}
  tls:
    secretName: grafana-tls
---
# Grafana HTTP to HTTPS redirect
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "observability-chart.fullname" . }}-grafana-http
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/grafana`)
      kind: Rule
      priority: 1000
      middlewares:
        - name: {{ include "observability-chart.fullname" . }}-redirect-https
          namespace: {{ .Release.Namespace }}
        - name: {{ include "observability-chart.fullname" . }}-grafana-strip-prefix
          namespace: {{ .Release.Namespace }}
      services:
        - name: {{ .Release.Name }}-grafana
          port: 80
{{- end }}
# ---
# # Kibana IngressRoute
# apiVersion: traefik.io/v1alpha1
# kind: IngressRoute
# metadata:
#   name: {{ include "observability-chart.fullname" . }}-kibana
#   namespace: {{ .Release.Namespace }}
#   labels:
#     {{- include "observability-chart.labels" . | nindent 4 }}
#     app.kubernetes.io/component: kibana
# spec:
#   entryPoints:
#     - web
#     - websecure
#   routes:
#     - match: Host(`{{ .Values.ingressroutes.domain }}`) && PathPrefix(`/kibana`)
#       kind: Rule
#       services:
#         - name: kibana
#           namespace: {{ .Values.global.namespace.name }}
#           port: 5601
#       middlewares:
#         - name: {{ include "observability-chart.fullname" . }}-kibana-headers
#           namespace: {{ .Release.Namespace }}
#         - name: {{ include "observability-chart.fullname" . }}-kibana-strip-prefix
#           namespace: {{ .Release.Namespace }}
#   tls:
#     secretName: kibana-tls
# ---
# # Kibana HTTP to HTTPS redirect
# apiVersion: traefik.io/v1alpha1
# kind: IngressRoute
# metadata:
#   name: {{ include "observability-chart.fullname" . }}-kibana-http
#   namespace: {{ .Release.Namespace }}
#   labels:
#     {{- include "observability-chart.labels" . | nindent 4 }}
#     app.kubernetes.io/component: kibana
# spec:
#   entryPoints:
#     - web
#   routes:
#     - match: Host(`{{ .Values.ingressroutes.domain }}`) && PathPrefix(`/kibana`)
#       kind: Rule
#       middlewares:
#         - name: {{ include "observability-chart.fullname" . }}-redirect-https
#           namespace: {{ .Release.Namespace }}
#         - name: {{ include "observability-chart.fullname" . }}-kibana-strip-prefix
#           namespace: {{ .Release.Namespace }}
#       services:
#         - name: kibana
#           namespace: {{ .Values.global.namespace.name }}
#           port: 5601
# {{- end }}
