{{- if index .Values "eck-kibana" "enabled" }}
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ index .Values "eck-kibana" "fullnameOverride" }}
  namespace: {{ .Values.global.namespace.name }}
  labels:
    {{- include "observability-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: kibana
  {{- with (index .Values "eck-kibana" "annotations") }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  version: {{ index .Values "eck-kibana" "version" }}
  count: {{ index .Values "eck-kibana" "spec" "count" | default 1 }}
  elasticsearchRef:
    name: {{ index .Values "eck-elasticsearch" "fullnameOverride" }}
    namespace: {{ .Values.global.namespace.name }}
  {{- if (index .Values "eck-kibana" "spec" "config") }}
  config:
    {{- toYaml (index .Values "eck-kibana" "spec" "config") | nindent 4 }}
  {{- end }}
  {{- if .Values.global.tls.enabled }}
  http:
    tls:
      selfSignedCertificate:
        disabled: false
  {{- end }}
  {{- if (index .Values "eck-kibana" "spec" "podTemplate") }}
  podTemplate:
    {{- toYaml (index .Values "eck-kibana" "spec" "podTemplate") | nindent 4 }}
  {{- end }}
  {{- with (index .Values "eck-kibana" "spec" "monitoring") }}
  monitoring:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
