{{- if (index .Values "eck-kibana").enabled }}
---
# Job to import Kibana dashboards and index patterns
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "observability-chart.fullname" . }}-kibana-setup
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: kibana-setup
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "observability-chart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: kibana-setup
    spec:
      restartPolicy: OnFailure
      containers:
      - name: kibana-setup
        image: curlimages/curl:8.1.2
        command:
        - /bin/sh
        - -c
        - |
          set -e
          echo "Waiting for Kibana to be ready..."
          
          # Wait for Kibana to be available
          until curl -s -k "https://eck-kibana-kb-http.default.svc.cluster.local:5601/api/status" \
            -u "elastic:${ELASTICSEARCH_PASSWORD}" \
            -H "Content-Type: application/json" | grep -q '"overall":{"level":"available"'; do
            echo "Kibana not ready yet, waiting..."
            sleep 10
          done
          
          echo "Kibana is ready, setting up index patterns and dashboards..."
          
          # Create index pattern
          curl -s -k -X POST "https://eck-kibana-kb-http.default.svc.cluster.local:5601/api/saved_objects/index-pattern/trascendence-logs-*" \
            -u "elastic:${ELASTICSEARCH_PASSWORD}" \
            -H "Content-Type: application/json" \
            -H "kbn-xsrf: true" \
            -d '{
              "attributes": {
                "title": "trascendence-logs-*",
                "timeFieldName": "@timestamp"
              }
            }' || echo "Index pattern may already exist"
          
          # Set as default index pattern
          curl -s -k -X POST "https://eck-kibana-kb-http.default.svc.cluster.local:5601/api/kibana/settings" \
            -u "elastic:${ELASTICSEARCH_PASSWORD}" \
            -H "Content-Type: application/json" \
            -H "kbn-xsrf: true" \
            -d '{
              "changes": {
                "defaultIndex": "trascendence-logs-*"
              }
            }' || echo "Default index already set"
          
          echo "✅ Kibana setup completed successfully!"
          
        env:
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: eck-elasticsearch-es-elastic-user
              key: elastic
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
{{- end }}
