{{- if index .Values "eck-logstash" "enabled" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ index .Values "eck-logstash" "fullnameOverride" }}-beats
  namespace: {{ .Values.global.namespace.name }}
  labels:
    {{- include "observability-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: logstash
spec:
  selector:
    common.k8s.elastic.co/type: logstash
    logstash.k8s.elastic.co/name: {{ index .Values "eck-logstash" "fullnameOverride" }}
  ports:
  - name: beats
    port: 5044
    targetPort: 5044
    protocol: TCP
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
{{- end }}
