{{- if and (hasKey .Values "certificates") .Values.certificates.enabled (hasKey .Values.certificates "services") (hasKey .Values.certificates.services "elasticsearch") .Values.certificates.services.elasticsearch.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elasticsearch-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: elasticsearch-tls
  duration: 2160h # 90 days
  renewBefore: 720h # 30 days
  commonName: {{ .Values.certificates.services.elasticsearch.commonName }}
  dnsNames:
    {{- range .Values.certificates.services.elasticsearch.dnsNames }}
    - {{ . }}
    {{- end }}
  issuerRef:
    name: {{ .Values.global.tls.issuer.name }}
    kind: {{ .Values.global.tls.issuer.kind }}
{{- end }}

{{- if and (hasKey .Values "certificates") .Values.certificates.enabled (hasKey .Values.certificates "services") (hasKey .Values.certificates.services "kibana") .Values.certificates.services.kibana.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kibana-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: kibana-tls
  duration: 2160h # 90 days
  renewBefore: 720h # 30 days
  commonName: {{ .Values.certificates.services.kibana.commonName }}
  dnsNames:
    {{- range .Values.certificates.services.kibana.dnsNames }}
    - {{ . }}
    {{- end }}
  issuerRef:
    name: {{ .Values.global.tls.issuer.name }}
    kind: {{ .Values.global.tls.issuer.kind }}
{{- end }}

{{- if and (hasKey .Values "certificates") .Values.certificates.enabled (hasKey .Values.certificates "services") (hasKey .Values.certificates.services "grafana") .Values.certificates.services.grafana.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: grafana-tls
  duration: 2160h # 90 days
  renewBefore: 720h # 30 days
  commonName: {{ .Values.certificates.services.grafana.commonName }}
  dnsNames:
    {{- range .Values.certificates.services.grafana.dnsNames }}
    - {{ . }}
    {{- end }}
  issuerRef:
    name: {{ .Values.global.tls.issuer.name }}
    kind: {{ .Values.global.tls.issuer.kind }}
{{- end }}
