{{- if .Values.serviceMonitors.enabled }}
{{- range .Values.serviceMonitors.services }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .name }}-monitor
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ .name }}
    monitoring: "true"
    {{- include "observability-chart.labels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .name }}
  endpoints:
  - port: "{{ .port }}"
    path: {{ .path | default "/metrics" }}
    interval: {{ .interval | default "30s" }}
{{- end }}
{{- end }}
