{{- if .Values.ingressroutes.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: kibana-tls-transport
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability-chart.labels" . | nindent 4 }}
spec:
  insecureSkipVerify: true
  # Remove serverName to avoid TLS verification issues
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Namespace }}-kibana-headers
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability-chart.labels" . | nindent 4 }}
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      X-Forwarded-Port: "443"
      X-Forwarded-Host: "kibana.{{ .Values.ingressroutes.domain }}"
    customResponseHeaders:
      X-Frame-Options: "SAMEORIGIN"
      X-Content-Type-Options: "nosniff"
{{- end }}
