apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "traefik-chart.fullname" . }}-config
  namespace: {{ include "traefik-chart.namespace" . }}
  labels:
    {{- include "traefik-chart.labels" . | nindent 4 }}
data:
  traefik.yml: |
    global:
      checkNewVersion: false
      sendAnonymousUsage: false
    
    entryPoints:
      web:
        address: ":80"
        http:
          redirections:
            entrypoint:
              to: websecure
              scheme: https
      websecure:
        address: ":443"
    
    api:
      dashboard: true
      insecure: true
    
    providers:
      kubernetesIngress: {}
      kubernetesCRD: {}
    
    log:
      level: INFO
    
    accessLog: {}
    
    metrics:
      prometheus:
        addEntryPointsLabels: true
        addServicesLabels: true
    
    ping: {}
