apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-login-db-service"
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-login-db
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-login-db
    release: {{ .Release.Name }}