apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: trascendence
  namespace: elk
spec:
  version: 8.13.4
  nodeSets:
  - name: trascendence
    count: 1
    config:
      node.store.allow_mmap: false