apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: trascendence
  namespace: elk
spec:
  version: 8.13.4
  nodeSets:
  - name: trascendence
    count: 1
    config:
      node.store.allow_mmap: false
  secureSettings:
  - secretName: elastic-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: trascendence-es-http
  namespace: elk
spec:
  selector:
    common.k8s.elastic.co/type: elasticsearch
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200