apiVersion: v2
name: trascendence
description: A Helm chart for Kubernetes, k3s

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"


dependencies:
  - name: trascendence-common
    version: "0.1.0"
    repository: "file://../trascendence-common"
  - name: front-end-chart
    repository: file://charts/front-end-chart
    version: 0.1.0
    condition: front-end.enabled
    tags:
      - front-end
  - name: chat-service-chart
    repository: file://charts/chat-service-chart
    version: 0.1.0
    condition: chat-service.enabled
    tags:
      - chat
  - name: login-service-chart
    repository: file://charts/login-service-chart
    version: 0.1.0
    tags:
      - login
  - name: user-service-chart
    repository: file://charts/user-service-chart
    version: 0.1.0
    tags:
      - user
  - name: notifications-service-chart
    repository: file://charts/notifications-service-chart
    version: 0.1.0
    tags:
      - notifications
  - name: pong-service-chart
    repository: file://charts/pong-service-chart
    version: 0.1.0
    tags:
      - pong
  # - name: api-docs-service-chart
  #   repository: file://charts/api-docs-service-chart
  #   version: 0.1.0
  #   condition: api-docs.enabled
  #   tags:
  #     - api-docs
  #     - documentation
  # - name: observability-chart
  #   repository: file://charts/observability-chart
  #   version: 0.1.0
  #   condition: observability.enabled
  #   tags:
  #     - observability
  #     - monitoring
  #     - logging
  - name: redis-chart
    repository: file://charts/redis-chart
    version: 0.1.0
    condition: redis.enabled
    tags:
      - redis
  - name: cert-manager-chart
    repository: file://charts/cert-manager-chart
    version: 0.1.0
    condition: cert-manager.enabled
    tags:
      - cert-manager