# Global values shared across all charts
global:
  environment: production

installCrds:
  enabled: true


# Frontend-specific overrides
frontend:
  hostAliases:
    - ip: "192.168.49.2"
      hostnames:
        - "trascendence.42firenze.it"
  image:
    repository: marcor42/frontend
    tag: latest

chat:
  image:
    repository: bombatomica/chat
    tag: latest
    pullPolicy: Always

  configMap:
    data:
    DEBUG: "True"
    DJANGO_SETTINGS_MODULE: "chat.settings"
    CHAT_PORT: "8000"
    CHAT_HOST: "0.0.0.0"
    DB_HOST: "postgres"
    DB_PORT: "5432"
    DB_NAME: "chat_db"
    DB_USER: "postgres"
    DB_PASSWORD: "postgres"
    REDIS_HOST: "redis"
    REDIS_PORT: "6379"
    REDIS_CHANNEL_DB: "1"
    LOGIN_URL: "http://login-service:8000"
    USER_URL: "http://user-service:8002"
    NOTIFICATIONS_URL: "http://notifications-service:8003"
    PONG_URL: "http://pong-service:8004"
    OAUTH2_INTROSPECTION_URL: "http://login-service:8000/o/introspect/"
    SERVICE_PASSWORD: "123"
    ALLOWED_HOSTS: "*"

secrets:
  database:
    name: "chat_db"
    user: "postgres"
    password: "postgres"
  admin:
    username: "admin"
    password: "adminpassword"
    email: "admin@example.com"
    secretKey: "your-secret-key"

cert-manager:
  enabled: true
  installCRDs: false
  
  # Default webhook config
  webhook:
    enabled: true
  
  # Ensure cert-manager cainjector is installed
  cainjector:
    enabled: true

persistence:
  enabled: true
  chat:
    enabled: true
    size: 512Mi

# Add these ingress settings to your umbrella chart values.yaml

front-end:
  enabled: true

chat-service:
  enabled: true

# Chart-specific overrides
front-end-chart:
  ingress:
    enabled: true
    host: trascendence.42firenze.it

chat-service-chart:
  ingress:
    enabled: true
    host: trascendence.42firenze.it
    path: /api/chat

# Umbrella-level settings
ingress:
  enabled: true
  className: traefik
  host: trascendence.42firenze.it
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer
  tls:
    enabled: true
    secretName: trascendence-tls


cert-manager-config:
  clusterIssuers:
    selfsigned:
      enabled: true
      name: selfsigned-issuer
    letsencrypt:
      enabled: false
      name: letsencrypt-prod
      email: qualcosa2001@gmail.com
      server: https://acme-v02.api.letsencrypt.org/directory
      privateKeySecretName: letsencrypt-prod
      solvers:
        - http01:
            ingressClass: traefik
    