# Global values shared across all charts
global:
  environment: production

# Frontend-specific overrides
frontend:
  hostAliases:
    - ip: "192.168.49.2"
      hostnames:
        - "trascendence.42firenze.it"
  image:
    repository: marcor42/frontend
    tag: latest

chat:
  image:
    repository: bombatomica/chat
    tag: latest
    pullPolicy: Always

  configMap:
    data:
    DEBUG: "True"
    DJANGO_SETTINGS_MODULE: "chat.settings"
    CHAT_PORT: "8000"
    CHAT_HOST: "0.0.0.0"
    DB_HOST: "postgres"
    DB_PORT: "5432"
    DB_NAME: "chat_db"
    DB_USER: "postgres"
    DB_PASSWORD: "postgres"
    REDIS_HOST: "redis"
    REDIS_PORT: "6379"
    REDIS_CHANNEL_DB: "1"
    LOGIN_URL: "http://login-service:8000"
    USER_URL: "http://user-service:8002"
    NOTIFICATIONS_URL: "http://notifications-service:8003"
    PONG_URL: "http://pong-service:8004"
    OAUTH2_INTROSPECTION_URL: "http://login-service:8000/o/introspect/"
    SERVICE_PASSWORD: "123"
    ALLOWED_HOSTS: "*"

secrets:
  database:
    name: "chat_db"
    user: "postgres"
    password: "postgres"
  admin:
    username: "admin"
    password: "adminpassword"
    email: "admin@example.com"
    secretKey: "your-secret-key"

