apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "pong-service-chart.fullname" . }}-ingress
  namespace: {{ include "pong-service-chart.namespace" . }}
  labels:
    {{- include "pong-service-chart.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certManager.clusterIssuer }}
    # Traefik specific annotations
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.priority: "1000"
    # WebSocket and HTTPS redirect middlewares
    traefik.ingress.kubernetes.io/router.middlewares: {{ include "pong-service-chart.namespace" . }}-{{ .Release.Name }}-websocket-headers,{{ include "pong-service-chart.namespace" . }}-{{ .Release.Name }}-redirect-https
    # Redirect HTTP to HTTPS
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        pathType: {{ .Values.ingress.pathType }}
        backend:
          service:
            name: "{{ .Release.Name }}-pong-service" # Fixed to match actual service name
            port:
              number: {{ .Values.service.port }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.tls.secretName }} # This should align with cert-manager or manual cert creation
  {{- end }}