{{- if .Values.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "pong-service-chart.namespace" . }}-{{ .Release.Name }}-websocket-headers
  namespace: {{ include "pong-service-chart.namespace" . }}
  labels:
    {{- include "pong-service-chart.labels" . | nindent 4 }}
spec:
  headers:
    customRequestHeaders:
      Connection: "upgrade"
      Upgrade: "websocket"
    customResponseHeaders:
      Connection: "upgrade"
      Upgrade: "websocket"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "pong-service-chart.namespace" . }}-{{ .Release.Name }}-redirect-https
  namespace: {{ include "pong-service-chart.namespace" . }}
  labels:
    {{- include "pong-service-chart.labels" . | nindent 4 }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{- end }}
