apiVersion: batch/v1
kind: Job
metadata:
  name: ensure-namespaces-{{ randAlphaNum 5 | lower }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-20"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    spec:
      serviceAccountName: default
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          # List of namespaces to ensure exist
          for ns in login front-end chat elk redis-namespace minio pong user notifications; do
            echo "Checking namespace: $ns"
            kubectl get namespace $ns > /dev/null 2>&1 || kubectl create namespace $ns
          done
      restartPolicy: Never