apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-websocket-headers
  namespace: {{ .Values.namespace }}
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
    customResponseHeaders:
      Connection: "Upgrade"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-redirect-https
  namespace: {{ .Values.namespace }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-strip-prefix
  namespace: {{ .Values.namespace }}
spec:
  stripPrefix:
    prefixes:
      - /api/chat
    forceSlash: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-traefik-crd-permissions # Renamed for clarity
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
rules:
- apiGroups:
  - "traefik.io" # Updated API Group
  resources:
  - middlewares
  - middlewaretcps
  - ingressroutes
  - ingressroutetcps
  - ingressrouteudps
  - tlsoptions
  - tlsstores
  - traefikservices
  # Add any other CRDs from traefik.io you might use
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-traefik-crd-binding # Renamed for clarity
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
subjects:
- kind: ServiceAccount
  name: traefik # Name of Traefik's ServiceAccount
  namespace: kube-system # Namespace of Traefik's ServiceAccount
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-traefik-crd-permissions # Updated to match new ClusterRole name
  apiGroup: rbac.authorization.k8s.io