apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-chat-db-pv
  labels:
    app: {{ .Release.Name }}
    type: chat-db
spec:
  capacity:
    storage: {{ .Values.persistence.chat.size | default "512Mi" }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/mnt/data/postgres/chat"