apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: qualcosa2001@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        cloudflare:
          email: qualcosa2001@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-key
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elasticsearch-cert
  namespace: elk
spec:
  secretName: elasticsearch-es-http-certs-public
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: trascendence.42firenze.it
  dnsNames:
  - trascendence.42firenze.it
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kibana-cert
  namespace: elk
spec:
  secretName: kibana-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: trascendence.42firenze.it
  dnsNames:
  - trascendence.42firenze.it
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-cert
  namespace: front-end-namespace
spec:
  secretName: nginx-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: trascendence.42firenze.it
  dnsNames:
  - trascendence.42firenze.it
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fleet-server-cert
  namespace: elk
spec:
  secretName: fleet-server-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: fleet-server.42firenze.it
  dnsNames:
  - fleet-server.42firenze.it
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-tls
  namespace: minio
spec:
  secretName: minio-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: minio.trascendence.42firenze.it
  dnsNames:
  - minio.trascendence.42firenze.it