name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - Back-End/task_user
          - Back-End/Notifications
          - Back-End/pongProject
          - Back-End/login
          - Back-End/chat
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd ${{ matrix.service }}
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: |
          cd ${{ matrix.service }}
          python manage.py test || echo "TESTS_FAILED=1" >> $GITHUB_ENV
